apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: EC2NodeClass
      name: cpu-base
    patch: |-
      - op: replace
        path: /metadata/name
        value: x86
      - op: replace
        path: /spec/amiSelectorTerms
        value:
          - alias: al2023@latest
      - op: add
        path: /spec/tags/Name
        value: "${CLUSTER_NAME}-karpenter-x86"
      - op: add
        path: /spec/tags/Architecture
        value: x86_64
