# VPC Outputs
output "vpc_id" {
  description = "The ID of the VPC"
  value       = aws_vpc.main.id
}

output "vpc_cidr" {
  description = "The CIDR block of the VPC"
  value       = aws_vpc.main.cidr_block
}

output "vpc_arn" {
  description = "The ARN of the VPC"
  value       = aws_vpc.main.arn
}

# Internet Gateway Outputs
output "internet_gateway_id" {
  description = "The ID of the Internet Gateway"
  value       = aws_internet_gateway.main.id
}

# Public Subnet Outputs
output "public_subnet_ids" {
  description = "List of IDs of public subnets"
  value       = aws_subnet.public[*].id
}

output "public_subnet_cidrs" {
  description = "List of CIDR blocks of public subnets"
  value       = aws_subnet.public[*].cidr_block
}

output "public_subnet_azs" {
  description = "List of availability zones of public subnets"
  value       = aws_subnet.public[*].availability_zone
}

# Individual Public Subnet IDs (useful for .env file)
output "public_subnet_a" {
  description = "Public subnet in first AZ"
  value       = aws_subnet.public[0].id
}

output "public_subnet_b" {
  description = "Public subnet in second AZ"
  value       = aws_subnet.public[1].id
}

output "public_subnet_c" {
  description = "Public subnet in third AZ"
  value       = aws_subnet.public[2].id
}

# Private Subnet Outputs
output "private_subnet_ids" {
  description = "List of IDs of private subnets"
  value       = aws_subnet.private[*].id
}

output "private_subnet_cidrs" {
  description = "List of CIDR blocks of private subnets"
  value       = aws_subnet.private[*].cidr_block
}

output "private_subnet_azs" {
  description = "List of availability zones of private subnets"
  value       = aws_subnet.private[*].availability_zone
}

# Individual Private Subnet IDs (useful for .env file)
output "private_subnet_a" {
  description = "Private subnet in first AZ"
  value       = aws_subnet.private[0].id
}

output "private_subnet_b" {
  description = "Private subnet in second AZ"
  value       = aws_subnet.private[1].id
}

output "private_subnet_c" {
  description = "Private subnet in third AZ"
  value       = aws_subnet.private[2].id
}

# NAT Gateway Outputs
output "nat_gateway_ids" {
  description = "List of NAT Gateway IDs"
  value       = var.enable_nat_gateway ? aws_nat_gateway.main[*].id : []
}

output "nat_gateway_public_ips" {
  description = "List of public IPs associated with NAT Gateways"
  value       = var.enable_nat_gateway ? aws_eip.nat[*].public_ip : []
}

# Route Table Outputs
output "public_route_table_id" {
  description = "ID of the public route table"
  value       = aws_route_table.public.id
}

output "private_route_table_ids" {
  description = "List of IDs of private route tables"
  value       = aws_route_table.private[*].id
}

# Availability Zones
output "availability_zones" {
  description = "List of availability zones used"
  value       = data.aws_availability_zones.available.names
}

# Summary output for easy reference
output "vpc_summary" {
  description = "Summary of VPC configuration"
  value = {
    vpc_id              = aws_vpc.main.id
    vpc_cidr            = aws_vpc.main.cidr_block
    public_subnets      = aws_subnet.public[*].id
    private_subnets     = aws_subnet.private[*].id
    availability_zones  = data.aws_availability_zones.available.names
    nat_gateway_count   = var.enable_nat_gateway ? (var.single_nat_gateway ? 1 : 3) : 0
  }
}

# Output formatted for .env file
output "env_file_format" {
  description = "VPC configuration formatted for .env file"
  value = <<-EOT
    # VPC Configuration (Generated by Terraform)
    VPC_ID=${aws_vpc.main.id}

    # Public Subnets
    PUBLIC_SUBNET_2A=${aws_subnet.public[0].id}
    PUBLIC_SUBNET_2B=${aws_subnet.public[1].id}
    PUBLIC_SUBNET_2C=${aws_subnet.public[2].id}

    # Private Subnets
    PRIVATE_SUBNET_2A=${aws_subnet.private[0].id}
    PRIVATE_SUBNET_2B=${aws_subnet.private[1].id}
    PRIVATE_SUBNET_2C=${aws_subnet.private[2].id}
  EOT
}
